detectorModel:
  minSize: 400
  staticPredictions: False
  confidenceThreshold: 0.9
  predictionClassesPath: 'maskRCNN/config/modelClasses.txt'
  staticPredictionsConfig:
    staticPredictionsInputPath: 'sampleImages/'
    staticPredictionsOutputPath: 'outputImages/'
segmentorModel:
  applyMaskProcessor: True
