detectorModel:
  minSize: 400
  staticPredictions: True
  confidenceThreshold: 0.9
  staticPredictionsConfig:
    staticPredictionsInputPath: 'sampleImages/'
    staticPredictionsOutputPath: 'outputImages/'
